import moment from 'moment'

const episodes = [
  {
    id: 1,
    title: 'Whitepaper Whitewashing & History of The Flippening',
    date: 'Friday, 22nd January 2021',
    dateRSS: new Date(2021, 0, 22),
    bchAddress: 'bitcoincash:qq0u3gej2rw9elpe42pp4cy25qknh2r0fvgfnpv7qm',
    mp3: "https://drive.google.com/file/d/1b_Ra-IX1Lxt6X4doRVeLnxOogsaLwl1a/view?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=_uimCmw1m9E',
  },
  {
    id: 2,
    title: 'Grassroots adoption & /r/wallstreetbets vs Wall Street',
    date: 'Thursday, 28th January 2021',
    dateRSS: new Date(2021, 0, 28),
    bchAddress: 'bitcoincash:qqldcn9p2qupgkmq4ctrqujyd4ju2m94y5fq680hye',
    mp3: "https://drive.google.com/file/d/1H4Hx3hGGA7iDQj5YluuC9sKGGNPUYmTM/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1wshYxnpvvBe_e4PnzNIEQwVCSCi8AAzldGyuHQNfLB8/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=voVS2omxMek',
  },
  {
    id: 3,
    title: 'Elon Musk hypes Bitcoin & Crypto Convert Q&A',
    date: 'Saturday, 30th January 2021',
    dateRSS: new Date(2021, 0, 30),
    bchAddress: 'bitcoincash:qzm49092tapkkuzvlr2q5hkv0un6rucq4vvspptszt',
    mp3: "https://drive.google.com/file/d/1ml9J4zMKoU8ogvGvgN5l2cDq3eO0jTgo/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1BpjPtjRl15VQ2ETqFG20ACtNu0lar3aXs5diLCsdIGc/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=6ZB9Oa2TUjk',
  },
  {
    id: 4,
    title: 'Community Debate & Bitcoin Cash vs Bitcoin',
    date: 'Sunday, 7th February 2021',
    dateRSS: new Date(2021, 1, 7),
    bchAddress: 'bitcoincash:qzkkzt34vdmf6rm98ndhhuf5l5d038jp25l7trwrl6',
    mp3: "https://drive.google.com/file/d/1W9cy6mfDvuRCsWgImO2oTvnKbQcAeTsC/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1XfZypaYYnkm74CNvkknhLx6BSVIWwY6fO5Pm110wCRI/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=2nC9xMLyPg4',
  },
  {
    id: 5,
    title: 'Tesla Buys Bitcoin & Why Cryptocurrencies',
    date: 'Wednesday, 10th February 2021',
    dateRSS: new Date(2021, 1, 10),
    bchAddress: 'bitcoincash:qre8lu4lasfn9kaxgaayhslh6wz2hvqtpvl2tgf75l',
    mp3: "https://drive.google.com/file/d/1HbMum9RvhoetM5Z1xvWLto2e0LOmNVF9/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1ebXNt-6AucTufG2xAW4L3j4jsLfORArH4j0Y23aAdDg/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=AEpQIEEcTUI',
  },
  {
    id: 6,
    title: 'Transaction Flippening & How Adoption Happens',
    date: 'Sunday, 21st February 2021',
    dateRSS: new Date(2021, 1, 21),
    bchAddress: 'bitcoincash:qq9tztlr2cqnx5m4plvsm93kjl3kv003dgg6suppj6',
    mp3: "https://drive.google.com/file/d/1zBdbPFPjW5YJlSn5RwS1PaQSOPs_0ylo/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1GA7bCSuxIK_Ss3jL7I3Piu2Xx7KkBkdD3zofATWBUnc/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=7wTBSyPkS2w',
  },
  {
    id: 7,
    title: 'Tether Investigation & Cryptocurrency Volatility',
    date: 'Sunday, 28th February 2021',
    dateRSS: new Date(2021, 1, 28),
    bchAddress: 'bitcoincash:qq57k9jgq9anfuvnp02z5zmav4kxs6jn7qzywcjh84',
    mp3: "https://drive.google.com/file/d/1wVFhFuA7kFmXyCCdIcV5F9ZNLAZYENAk/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1AuN_Z6pMBfOjHipi2WlvO9302HjF-PIQhv2YowfKqj8/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=PYUj7VqVJ_U',
  },
  {
    id: 8,
    title: 'The Path To Global Adoption',
    date: 'Sunday, 7th March 2021',
    dateRSS: new Date(2021, 2, 7),
    bchAddress: 'bitcoincash:qq62hdqp0hsa23qtevknnqy5nu03nwjn5u9fh4ypjr',
    mp3: "https://drive.google.com/file/d/1GHMQoOHVb5XRMRCwh2-LJP5SCcVdOARk/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1rOvOaAzGc-xAw39KtvK1p3erZpNIrh_vUIdS0cvUgzM/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=chaOSbdZsPk',
  },
  {
    id: 9,
    title: 'Bitcoin Forks & Adoption In Detroit',
    date: 'Wednesday, 10th March 2021',
    dateRSS: new Date(2021, 2, 10),
    bchAddress: 'bitcoincash:qq62hdqp0hsa23qtevknnqy5nu03nwjn5u9fh4ypjr',
    mp3: "https://drive.google.com/file/d/1jga8KYTVb0SBdVHV44dq5_uaB21q0wBh/view?usp=sharing",
    slideDeck: "https://docs.google.com/presentation/d/1IFQB93rRJ7C7XENrTxZgpLs3yM_GCcxlwu19-cm2WCo/edit?usp=sharing",
    youtube: 'https://www.youtube.com/watch?v=lCucgcEevVw',
  },
  {
    id: 10,
    title: 'Cryptocurrency gets cool & the Bitcoin (BTC) Bubble',
    date: 'Wednesday, 17th March 2021',
    dateRSS: new Date(2021, 2, 17),
    bchAddress: 'bitcoincash:qrxxgp6wkc2k90xej9r8y8xc7t98ecykmy58m3z8fm',
    mp3: "",
    slideDeck: "https://docs.google.com/presentation/d/1rjZ4VQqiXkuyY7CWPGIcHEVhIWx0Y2_4ANf_43Hi3O4/edit?usp=sharing",
    youtube: '',
  }
]

export default episodes